---
title: "R Notebook"
output: html_notebook
---



```{r}
pos <- replicate(1000, sum(runif(16, -1, 1)))
plot(pos)
hist(pos)
pos <- replicate(1000, log(prod(1 + runif(12, 0, 0.5))))
dens(pos, norm.comp=T)
```
```{r }
num = 1000
w = 6; n = 9
p_grid = seq(0, 1, length.out=num)
posterior = dbinom(w, n, p_grid) * dunif(p_grid, 0, 1)
posterior = posterior / sum(posterior)
plot(posterior)
```
The plot looks similar as model solved using grid calculation in previous chapters.

```{r data}
library(rethinking)
data(Howell1)
d = Howell1
str(d)
# plot density of height
dens(d$height)
curve( dnorm(x, 178, 20), from = 100, to=250)
curve( dunif( x , 0 , 50 ) , from=-10 , to=60 )

sample_mu = rnorm(1e4, 178, 20)
sample_sigma = runif(1e4, 0, 50)
prior_h = rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```
```{r code 4.14 grid approximation}
d2 <- d[ d$age >= 18 , ]
mus = seq(140, 160, length.out=200)
sigs = seq(4, 9, length.out=200)
post = expand.grid(mu=mus, sigma=sigs)
get_dist = function(i,post) {
  sum(dnorm(d2$height, mean=post$mu[i], sd=post$sigma[i],
            log=TRUE))
}
post$LL = sapply(1:nrow(post), get_dist, post=post)
post$prob = post$LL + dnorm(post$mu, 178, 20, TRUE) + 
       dunif(post$sigma, 0, 50, TRUE)
post$prob = exp(post$prob - max(post$prob))
contour_xyz( post$mu , post$sigma , post$prob )
image_xyz(post$mu, post$sigma, post$prob)
```

```{r sample the post code 4.17}
sample.rows = sample(1:nrow(post), 1e4, replace=TRUE, prob=post$prob)
sample.mu = post$mu[sample.rows]
sample.sigma = post$sigma[sample.rows]
plot( sample.mu , sample.sigma , cex=0.5 , pch=16 , col=col.alpha(rangi2,0.1) )
dens(sample.mu)
dens(sample.sigma)
HPDI(sample.mu)
HPDI(sample.sigma)
```
```{r test sigma does not alway follow normal distribution, code 4.21}
d3 = sample(d2$height, size = 20)
mu.list <- seq( from=150, to=170 , length.out=200 )
sigma.list <- seq( from=4 , to=20 , length.out=200 )
post2 <- expand.grid( mu=mu.list , sigma=sigma.list )
post2$LL <- sapply( 1:nrow(post2) , function(i)
  sum( dnorm( d3 , mean=post2$mu[i] , sd=post2$sigma[i] ,
  log=TRUE ) ) )
post2$prod <- post2$LL + dnorm( post2$mu , 178 , 20 , TRUE ) +
    dunif( post2$sigma , 0 , 50 , TRUE )
post2$prob <- exp( post2$prod - max(post2$prod) )
sample2.rows <- sample( 1:nrow(post2) , size=1e4 , replace=TRUE ,
prob=post2$prob )
sample2.mu <- post2$mu[ sample2.rows ]
sample2.sigma <- post2$sigma[ sample2.rows ]
plot( sample2.mu , sample2.sigma , cex=0.5 ,
col=col.alpha(rangi2,0.1) ,
xlab="mu" , ylab="sigma" , pch=16 )
dens(sample2.sigma)
```
```{r quadratic maximization}
library(rethinking)
data(Howell1)
d <- Howell1
d2 <- d[ d$age >= 18 , ]

flist = alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 20),
    sigma ~ dunif(0, 50)
)
m4.1 = map(flist, data=d2)
precis(m4.1)
vcov(m4.1)
# set start value for qudratic optimization
start <- list(
mu=mean(d2$height),
sigma=sd(d2$height)
)
```

```{r narrow the variance, code 4.29}
m4.2 <- map(
  alist(
  height ~ dnorm( mu , sigma ) ,
  mu ~ dnorm( 178 , 0.1 ) ,
  sigma ~ dunif( 0 , 50 )
  ) ,
  data=d2 )
precis( m4.2 )
```
```{r 4.29}
vcov(m4.1)
diag(vcov(m4.1))
cov2cor(vcov(m4.1))
```


```{r extract samples for sampling, code 4.32}
library(rethinking)
post_param = extract.samples(m4.1, n=1e4)
precis(post_param)
plot(post_param$mu, post_param$sigma)
```
```{r sample using mvrnorm, code 4.34}
library(MASS)
post.samples = mvrnorm(n=1e4, mu=coef(m4.1), Sigma=vcov(m4.1))
```

```{r log of sigma, code 4.35}
m4.1_logsigma <- map(
    alist(
    height ~ dnorm( mu , exp(log_sigma) ) ,
    mu ~ dnorm( 178 , 20 ) ,
    log_sigma ~ dnorm( 2 , 10 )
    ) , data=d2 )

post = extract.samples(m4.1_logsigma)
sigma = exp(post$log_sigma)
```

4.4 add predictor
```{r, code 4.37}
plot( d2$height ~ d2$weight )
```
```{r, code 4.38}
library(rethinking)
data(Howell1)
d <- Howell1
d2 <- d[ d$age >= 18 , ]

m4.3 <- map(
    alist(
        height ~ dnorm(mu, sigma),
        mu <- a + b*weight,
        a ~ dnorm(156, 100),
        b ~ dnorm(0, 10), 
        sigma ~ dunif(0,50)
    ), data=d2
)
```

```{r code 4.39}
m4.3 <- map(
  alist(
    height ~ dnorm( a + b*weight , sigma ) ,
    a ~ dnorm( 178 , 100 ) ,
    b ~ dnorm( 0 , 10 ) ,
    sigma ~ dunif( 0 , 50 )
    ) ,
    data=d2 )
```

```{r code 4.40, 4.41}
precis(m4.3, corr=T)
cov2cor(vcov(m4.3))
```
```{r code 4.42}
d2$weight.c <- d2$weight - mean(d2$weight)
mean(d2$weight.c)

m4.4 <- map(
    alist(
        height ~ dnorm(mu, sigma),
        mu <- a + b*weight.c,
        a ~ dnorm(156, 100),
        b ~ dnorm(0, 10), 
        sigma ~ dunif(0,50)
    ), data=d2
)
precis(m4.4, corr=T)
cov2cor(vcov(m4.4))
```
```{r code 4.45, posterior against data}
plot(height ~ weight, data=d2)
abline(a=coef(m4.3)["a"], b=coef(m4.3)["b"])

post = extract.samples(m4.3)
```
4.4.3.3. Adding uncertainty around the mean
```{r code 4.48}
N <- 352
dN <- d2[ 1:N , ]
mN <- map(
  alist(
    height ~ dnorm( mu , sigma ) ,
    mu <- a + b*weight ,
    a ~ dnorm( 178 , 100 ) ,
    b ~ dnorm( 0 , 10 ) ,
    sigma ~ dunif( 0 , 50 )
  ) , data=dN )
# extract 20 samples from the posterior
post <- extract.samples( mN , n=20)
```
```{r code 4.49}
# display raw data and sample size
plot( dN$weight , dN$height ,
    xlim=range(d2$weight) , ylim=range(d2$height) ,
    col=rangi2 , xlab="weight" , ylab="height" )
mtext(concat("N = ",N))
# plot the lines, with transparency
for ( i in 1:20 )
  abline( a=post$a[i] , b=post$b[i] , col=col.alpha("black",0.3) )
```
4.4.3.4. Plotting regression intervals and contours
```{r code 4.50}
mu_at_50 = post$a + post$b * 50
dens(mu_at_50, col=rangi2, lwd=2, xlab="mu|weight=50")
```
```{r code 4.52}
HPDI(mu_at_50, prob=0.89)
```
```{r code 4.53}
mu = link(m4.3)
str(mu)
```
```{r code 4.54}
# define sequence of weights to compute predictions for 4.54
# these values will be on the horizontal axis
weight.seq <- seq( from=25 , to=70 , by=1 )
# use link to compute mu
# for each sample from posterior
# and for each weight in weight.seq
mu <- link( m4.3 , data=data.frame(weight=weight.seq) )
str(mu)
```
```{r code 4.55}
# use type="n" to hide raw data 4.55
plot( height ~ weight , d2 , type="n" )
for ( i in 1:100 )
  points( weight.seq , mu[i,] , pch=16 , col=col.alpha(rangi2,0.1) )
```
```{r code4.56}
mu.mean = apply(mu, 2, mean)
mu.HPDI = apply(mu, 2, HPDI, prob=0.89)

# plot raw data
plot(height ~ weight, data=d2, col=col.alpha(rangi2, 0.5))
# plot map line
lines(weight.seq, mu.mean)
# plot shaded regions for 89% HPDI
shade(mu.HPDI, weight.seq)
```
Summary:
1. Use link to generate distribution of mu.
2. Use summary function to get a sense of mu and HDPI.
3. plot the lines and shade.
```{r code 4.58}
post <- extract.samples(m4.3) 
mu.link <- function(weight) post$a + post$b*weight
weight.seq <- seq( from=25 , to=70 , by=1 )
mu <- sapply( weight.seq , mu.link )
mu.mean <- apply( mu , 2 , mean )
mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 )
```
4.4.3.5 Prediction intervals
```{r code 4.59}
sim.height = sim(m4.3, data=list(weight=weight.seq))
str(sim.height)
height.PI = apply(sim.height, 2, PI, prob=0.89)
```
```{r code 4.61}
# plot raw data
plot( height ~ weight , d2 , col=col.alpha(rangi2,0.5) )
# draw MAP line
lines( weight.seq , mu.mean )
# draw HPDI region for line
shade( mu.HPDI , weight.seq )
# draw PI region for simulated heights
shade( height.PI , weight.seq )
```
```{r code 4.63}
post <- extract.samples(m4.3)
weight.seq <- 25:70
sim.height <- sapply( weight.seq , function(weight)
    rnorm(
      n=nrow(post) ,
      mean=post$a + post$b*weight ,
      sd=post$sigma ) )
height.PI <- apply( sim.height , 2 , PI , prob=0.89 )
```
4.5 Polynomial regression
```{r code 4.64}
library(rethinking)
data(Howell1)
d = Howell1
plot(d$height, d$weight, xlab='height', ylab='weight')
summary(d)
```
```{r code 4.65}
d$weight.s = (d$weight - mean(d$weight)) / sd(d$weight)
plot(d$height, d$weight.s)
```
```{r code 4.66}
d$weight.s2 = d$weight.s^2
m4.5 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1 * weight.s + b2 * weight.s2,
    a ~ dnorm(178, 100),
    b1 ~ dnorm(0,10),
    b2 ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
    ), data = d
)
precis(m4.5)
```
```{r code 4.68}
weight.seq = seq(from=-2.2, to=2, length.out=30)
pred_dat = list(weight.s=weight.seq, weight.s2=weight.seq^2)
mu = link(m4.5, data=pred_dat)
mu.mean = apply(mu, 2, mean)
mu.PI = apply(mu, 2, PI, prob=0.89)
sim.height = sim(m4.5, data=pred_dat)
height.PI = apply(sim.height, 2, PI, prob=0.89)
```

```{r code 4.69 plot }
plot(height ~ weight.s, d, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```
```{r code 4.70} 
d$weight.s3 = d$weight.s^3
m4.6 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight.s + b2*weight.s2 + b3*weight.s3,
    a ~ dnorm(178, 100),
    b1 ~ dnorm(0,10),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
    ), data = d
)
precis(m4.6)
```
```{r}
weight.seq = seq(from=-2.2, to=2, length.out=30)
pred_dat = list(weight.s=weight.seq, weight.s2=weight.seq^2, weight.s3=weight.seq^3)
mu = link(m4.6, data=pred_dat)
mu.mean = apply(mu, 2, mean)
mu.PI = apply(mu, 2, PI, prob=0.89)
sim.height = sim(m4.5, data=pred_dat)
height.PI = apply(sim.height, 2, PI, prob=0.89)
```
```{r}
plot(height ~ weight.s, d, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
```


```{r 4.71}
plot(height ~weight.s, d, col=col.alpha(rangi2,0.5), xaxt="n")
at = c(-2, -1, 0, 1, 2)
labels = at * sd(d$weight) + mean(d$weight)
axis(side=1, at=at, labels=round(labels, 1))
```
