---
title: "Chapter 3"
output: html_notebook
---


```{r get posterior probability}
library(rethinking)

n = 1000
# define grid
p_grid <- seq(0, 1, length.out=n)
# define prior
prior <- rep(1, n)
# compute likelihood at each value in grid
likelihood <- dbinom(6, size=9, prob = p_grid)
# compute product of prior and likelihood
unstd_post <- prior * likelihood
# normalize post
post <- unstd_post / sum(unstd_post)

samples <- sample(p_grid, prob=post, size=1e4, replace=TRUE)
plot(samples)
dens(samples)
plot(post)
```
```{r 3.2 sample}
sum(post[p_grid < 0.5])
sum(samples < 0.5) / 1e4
```

```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep(1,1000)
likelihood <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
samples <- sample( p_grid , size=1e4 , replace=TRUE , prob=posterior )
PI(samples, prob=0.5)

p_grid[which.max(posterior)]
# determine loss values
loss <- sapply(p_grid,function(d) {sum(posterior * abs(d-p_grid))})
p_grid[which.min(loss)]

dummy_w <- rbinom(1e5, size=9, prob=0.7)

w <- rbinom( 1e4 , size=9 , prob=samples )
simplehist(w)
```

